### PR TITLE
Replace library loading section with a single sourced script. Resolves #50.

### LINKED ISSUE #50: Include a script to check for/load packages
Might be worth it to have this step run automatically to prevent errors, rather than listing the libraries.

Example:
https://github.com/HerreraEnvironmental/21-07771-003_ShorelineChangeAnalysis/blob/main/scripts/src/load_packages.R

### PR DESCRIPTION
**Pull request by R-Lionheart**

### CODE REVIEW

**Comment by clarkbar88** [comment]
Oo. Love it.
Can you tell me how to interpret about the "conda installed" message?

**Comment by R-Lionheart** [comment]
We can probably just get rid of that part. I was wondering if this script would cause problems for users who exclusively use conda or another package/environment manager by using the default installation paths instead of conda paths. But I'm not sure it will be an issue since I use conda and I also use this script in my projects. We could always pose a quick question for first time users ("These packages are required: do you want them installed?").

**Comment by clarkbar88** [comment]
@R-Lionheart 
There is an error that occurs when deployed to ShinyApps. I think it might be related to trying to install packages within a shiny instance.
This code won't work for a deployment, but is useful for the initial setup and running locally. 

> 2023-08-29T17:54:38.433609+00:00 shinyapps[9419341]: jsonlite version: 1.8.4
> 2023-08-29T17:54:38.438780+00:00 shinyapps[9419341]: RJSONIO version: (none)
> 2023-08-29T17:54:38.443810+00:00 shinyapps[9419341]: htmltools version: 0.5.4
> 2023-08-29T17:54:38.449535+00:00 shinyapps[9419341]: reticulate version: (none)
> 2023-08-29T17:54:38.454837+00:00 shinyapps[9419341]: Using pandoc: /opt/connect/ext/pandoc/2.16
> 2023-08-29T17:54:38.459926+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:38.465373+00:00 shinyapps[9419341]: Starting R with process ID: '35'
> 2023-08-29T17:54:38.470948+00:00 shinyapps[9419341]: Shiny application starting ...
> 2023-08-29T17:54:38.476491+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:38.481839+00:00 shinyapps[9419341]: Listening on http://127.0.0.1:46279
> 2023-08-29T17:54:39.360053+00:00 shinyapps[9419341]: sh: 1: conda: not found
> 2023-08-29T17:54:39.365512+00:00 shinyapps[9419341]: Warning in system("conda --version") : error in running command
> 2023-08-29T17:54:39.371005+00:00 shinyapps[9419341]: Loading required package: bslib
> 2023-08-29T17:54:39.376371+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:39.381488+00:00 shinyapps[9419341]: Attaching package: ‘bslib’
> 2023-08-29T17:54:39.387686+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:39.393160+00:00 shinyapps[9419341]: The following object is masked from ‘package:utils’:
> 2023-08-29T17:54:39.398272+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:39.403323+00:00 shinyapps[9419341]:     page
> 2023-08-29T17:54:39.408434+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:39.413692+00:00 shinyapps[9419341]: Loading required package: dplyr
> 2023-08-29T17:54:40.359550+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.365083+00:00 shinyapps[9419341]: Attaching package: ‘dplyr’
> 2023-08-29T17:54:40.370365+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.376127+00:00 shinyapps[9419341]: The following objects are masked from ‘package:stats’:
> 2023-08-29T17:54:40.381334+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.386455+00:00 shinyapps[9419341]:     filter, lag
> 2023-08-29T17:54:40.392941+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.397904+00:00 shinyapps[9419341]: The following objects are masked from ‘package:base’:
> 2023-08-29T17:54:40.405746+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.411590+00:00 shinyapps[9419341]:     intersect, setdiff, setequal, union
> 2023-08-29T17:54:40.416959+00:00 shinyapps[9419341]: 
> 2023-08-29T17:54:40.422280+00:00 shinyapps[9419341]: Loading required package: DT
> 2023-08-29T17:54:40.427661+00:00 shinyapps[9419341]: Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
> 2023-08-29T17:54:40.433184+00:00 shinyapps[9419341]:   there is no package called ‘DT’
> 2023-08-29T17:54:40.438410+00:00 shinyapps[9419341]: Warning in install.packages(Package, dependencies = TRUE) :
> 2023-08-29T17:54:40.443520+00:00 shinyapps[9419341]:   'lib = "/opt/R/4.2.1/lib/R/library"' is not writable
> 2023-08-29T17:54:40.448893+00:00 shinyapps[9419341]: Warning: Error in install.packages: unable to install packages
> 2023-08-29T17:54:40.453978+00:00 shinyapps[9419341]:   81: stop
> 2023-08-29T17:54:40.459173+00:00 shinyapps[9419341]:   80: install.packages
> 2023-08-29T17:54:40.464632+00:00 shinyapps[9419341]:   15: <Anonymous>
> 2023-08-29T17:54:40.469954+00:00 shinyapps[9419341]:   13: fn
> 2023-08-29T17:54:40.475507+00:00 shinyapps[9419341]:    8: retry
> 2023-08-29T17:54:40.481538+00:00 shinyapps[9419341]:    7: connect$retryingStartServer
> 2023-08-29T17:54:40.488583+00:00 shinyapps[9419341]:    6: eval
> 2023-08-29T17:54:40.494081+00:00 shinyapps[9419341]:    5: eval
> 2023-08-29T17:54:40.499424+00:00 shinyapps[9419341]:    4: eval
> 2023-08-29T17:54:40.504968+00:00 shinyapps[9419341]:    3: eval
> 2023-08-29T17:54:40.510414+00:00 shinyapps[9419341]:    2: eval.parent
> 2023-08-29T17:54:40.515712+00:00 shinyapps[9419341]:    1: loca

l

**Comment by clarkbar88** [comment]
I'm guessing the error came up because we don't use any DT:: functions in the code, so it wasn't required in the shinyapps deployment. This would cause the load_packages.R script to try to install DT, which would then fail.

**Comment by clarkbar88** [comment]
This package check might be more appropriate in the "data_prep.R" script which is used when updating the input data.

**Comment by R-Lionheart** [comment]
Sounds good to me! Good to know that this isn't a good fix for deployment.

**Pull request closed without merging**
